# Generated by Django 2.1.7 on 2019-03-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.TimeField(auto_now=True)),
            ],
        ),
    ]
